In [38]:
import pandas as pd
import numpy
import matplotlib.pyplot
import os

In [39]:
DATA_DIR = os.path.dirname(os.path.abspath('')) + '\\data\\03_processed\\'
df = pd.read_csv(DATA_DIR + 'processed_durham.csv')
print('Total number of records: ' , df.shape[0])
#df

Total number of records:  2535

In [40]:
top_10_sector = df.query('Salary_crnt > 100000').groupby('Sector')['LastName'].count() \
    .reset_index(name='count') \
    .sort_values(['count'], ascending=False) \
    .head(10)
top_10_sector

                          Sector  count
1      Municipalities & Services   1380
3                  School Boards    853
0                       Colleges    255
2  Other Public Sector Employers     46
4           Seconded (Education)      1

In [41]:
top_10_employers = df.query('Salary_crnt > 100000').groupby('Employer')['LastName'].count() \
    .reset_index(name='count') \
    .sort_values(['count'], ascending=False) \
    .head(10)
top_10_employers

                                            Employer  count
8                    Regional Municipality Of Durham   1380
5                       Durham District School Board    541
2              Durham Catholic District School Board    313
4      Durham College Of Applied Arts and Technology    255
3                      Durham Children’s Aid Society     38
1        Canadian Mental Health Association – Durham      2
10                    West Durham Family Health Team      2
0                 Alzheimer Society Of Durham Region      1
6                    North Durham Family Health Team      1
7   Participation House Project (Durham Region ) Inc      1

In [42]:
top_10_salaries = df.query('Salary_crnt > 100000') \
    [['Sector', 'Employer', 'JobTitle', 'Salary_crnt', 'Salary_prev', 'PrcntSalaryDiff']] \
    .sort_values(['Salary_crnt'], ascending=False) \
    .head(10)
top_10_salaries

,Sector,Employer,JobTitle,Salary_crnt,Salary_prev,PrcntSalaryDiff
961,Municipalities & Services,Regional Municipality Of Durham,Commissioner and Medical Officer of Health,535190.04,337142.41,58.74
692,Municipalities & Services,Regional Municipality Of Durham,"Director, Health Protection",316933.85,174398.22,81.73
339,Municipalities & Services,Regional Municipality Of Durham,Chief Administrative Officer,315499.17,318724.05,-1.01
1171,Municipalities & Services,Regional Municipality Of Durham,"Director, Population Health and Chief Nursing ...",314139.15,172283.88,82.34
1125,Municipalities & Services,Regional Municipality Of Durham,"Assistant Manager, Population Health",308798.44,131154.59,135.45
150,Colleges,Durham College Of Applied Arts and Technology,President,302745.30,302745.30,0.00
504,Municipalities & Services,Regional Municipality Of Durham,"Manager, Community and Resource Development",294561.43,117722.52,150.22
2187,School Boards,Durham District School Board,Director of Education,283768.46,271280.76,4.60
794,Municipalities & Services,Regional Municipality Of Durham,"Manager, Population Health",277661.56,144060.50,92.74
884,Municipalities & Services,Regional Municipality Of Durham,"Manager, Population Health",252832.97,143728.59,75.91

In [43]:
top_10_increases = df.query('Salary_crnt > 100000') \
    [['Sector', 'Employer', 'JobTitle', 'Salary_crnt', 'Salary_prev', 'PrcntSalaryDiff']] \
    .sort_values(['PrcntSalaryDiff'], ascending=False) \
    .head(10)
top_10_increases

,Sector,Employer,JobTitle,Salary_crnt,Salary_prev,PrcntSalaryDiff
504,Municipalities & Services,Regional Municipality Of Durham,"Manager, Community and Resource Development",294561.43,117722.52,150.22
1125,Municipalities & Services,Regional Municipality Of Durham,"Assistant Manager, Population Health",308798.44,131154.59,135.45
1066,Municipalities & Services,Regional Municipality Of Durham,"Manager, Health Protection",239330.05,119532.96,100.22
794,Municipalities & Services,Regional Municipality Of Durham,"Manager, Population Health",277661.56,144060.50,92.74
409,Municipalities & Services,Regional Municipality Of Durham,"Assistant Manager, Population Health",245996.34,131036.03,87.73
1171,Municipalities & Services,Regional Municipality Of Durham,"Director, Population Health and Chief Nursing ...",314139.15,172283.88,82.34
692,Municipalities & Services,Regional Municipality Of Durham,"Director, Health Protection",316933.85,174398.22,81.73
474,Municipalities & Services,Regional Municipality Of Durham,"Manager, Administration",192011.21,108381.71,77.16
960,Municipalities & Services,Regional Municipality Of Durham,"Manager, Health Protection",251264.45,142594.74,76.21
884,Municipalities & Services,Regional Municipality Of Durham,"Manager, Population Health",252832.97,143728.59,75.91

In [45]:
salary_increased = df.query('PrcntSalaryDiff > 0')
print('Total salaries increased = ' , salary_increased.shape[0] , 
    ' i.e. ' , numpy.round(100*salary_increased.shape[0]/df.shape[0], decimals=2) , '% of total salaries')

salary_decreased = df.query('PrcntSalaryDiff < 0')
print('Total salaries decreased = ' , salary_decreased.shape[0] , 
    ' i.e. ' , numpy.round(100*salary_decreased.shape[0]/df.shape[0], decimals=2) , '% of total salaries')

salary_remained_same = df.query('PrcntSalaryDiff == 0')
print('Total salaries remained same = ' , salary_remained_same.shape[0] , 
    ' i.e. ' , numpy.round(100*salary_remained_same.shape[0]/df.shape[0], decimals=2) , '% of total salaries')

Total salaries increased =  1664  i.e.  65.64 % of total salaries
Total salaries decreased =  860  i.e.  33.93 % of total salaries
Total salaries remained same =  11  i.e.  0.43 % of total salaries

,Unnamed: 0,Sector,LastName,FirstName,Salary_crnt,Benefits_crnt,Employer,JobTitle,Year_crnt,_docID,Salary_prev,Benefits_prev,Year_prev,Salary_diff,PrcntSalaryDiff,Benefits_diff,PrcntBenefitDiff
18,356,Colleges,Beaudoin,Isabelle,115648.84,124.44,Durham College Of Applied Arts and Technology,Professor,2021,460,115650.07,117.26,2020,-1.23,-0.0,7.18,6.12
24,492,Colleges,Blakey,Scott,198203.20,12572.82,Durham College Of Applied Arts and Technology,Chief Administrative Officer,2021,638,198203.20,10579.94,2020,0.00,0.0,1992.88,18.84
150,3306,Colleges,Lovisa,Don,302745.30,13846.62,Durham College Of Applied Arts and Technology,President,2021,4215,302745.30,13634.86,2020,0.00,0.0,211.76,1.55
153,3346,Colleges,Maccheyne,Barbara,191312.16,12854.83,Durham College Of Applied Arts and Technology,Vice President Administration and Chief Financ...,2021,4262,191312.06,10785.76,2020,0.10,0.0,2069.07,19.18
996,61666,Municipalities & Services,Lee,Chad K,129139.88,635.14,Regional Municipality Of Durham,Police – Detective Constable,2021,96855,129141.99,628.65,2020,-2.11,-0.0,6.49,1.03
1177,67472,Municipalities & Services,Nimmo,Tavis D,117728.04,683.56,Regional Municipality Of Durham,"Supervisor, Technical Support",2021,105351,117722.52,674.37,2020,5.52,0.0,9.19,1.36
1239,69001,Municipalities & Services,Pereira,Gregory,139443.43,827.01,Regional Municipality Of Durham,"Manager, Transportation Planning",2021,107631,139445.94,799.23,2020,-2.51,-0.0,27.78,3.48
1405,73654,Municipalities & Services,Simpson,Jennifer Joan,117728.03,683.56,Regional Municipality Of Durham,"Supervisor, Income Support",2021,114396,117722.53,674.37,2020,5.50,0.0,9.19,1.36
1440,74770,Municipalities & Services,Stein,Derrick,107014.36,621.55,Regional Municipality Of Durham,"Officer, Health and Safety",2021,116071,107009.64,612.51,2020,4.72,0.0,9.04,1.48
1625,79456,Municipalities & Services,Yu,Donald F,129499.59,751.48,Regional Municipality Of Durham,"Engineer, Environmental Services Design",2021,123000,129494.27,741.60,2020,5.32,0.0,9.88,1.33
1758,93837,School Boards,Boehm,Lisa,113027.98,1350.00,Durham Catholic District School Board,Elementary Vice Principal,2021,147282,113027.98,1350.00,2020,0.00,0.0,0.00,0.00